hadron: dstar

input:
  data: inputs/sparse_dstar_LHC22_LHC23.root
  mc: [inputs/sparse_dstar_LHC24g5_trackTuner_ptSmearing1p5.root, inputs/sparse_dstar_LHC24h1_trackTuner_ptSmearing1p5.root]
  mc_weights: [1., 2.3333] # 1 and 7./3 which approximatelly should reproduce the data 

pt_mins: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10., 12., 16.]
pt_maxs: [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10., 12., 16., 24.]

bdt_cuts:
  bkg: [0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06]
  nonprompt: [0.20, 0.22, 0.24, 0.26, 0.28,
              0.30, 0.32, 0.34, 0.36, 0.38,
              0.40, 0.42, 0.44, 0.46, 0.48,
              0.50, 0.52, 0.54, 0.56, 0.58,
              0.60, 0.62, 0.64, 0.66, 0.68,
              0.70, 0.72, 0.74, 0.76, 0.78,
              0.80, 0.82, 0.84, 0.86, 0.88,
              0.90, 0.92, 0.94, 0.96, 0.98] # values for cut-variation method (pT differential?)

fit:
  mass_mins: [0.1396, 0.1396, 0.1396, 0.1396, 0.1396, 0.1396, 0.1396, 0.1396, 0.1396, 0.1396, 0.1396, 0.1396]
  mass_maxs: [0.160, 0.165, 0.1700, 0.1700, 0.1700, 0.1700, 0.1700, 0.1700, 0.1700, 0.1700, 0.1700, 0.1700]
  sgn_funcs: ["doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb"]
  bkg_funcs: ["expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext"]

efficiency:
  include_pitomu: True

output:
  rawyields:
    directory: rawyields
    suffix: _dstar_LHC22_LHC23
  efficiencies:
    directory: efficiencies
    suffix: _dstar_LHC24g5_LHC24h1_trackTuner_ptSmearing1p5 #