hadron: dplus

input:
  data: inputs/sparse_dplus_LHC22_LHC23_MB_full.root
  mc: [inputs/sparse_dplus_MBcuts_LHC24g5_train297397.root, inputs/sparse_dplus_MBcuts_LHC24h1_train298922.root]
  mc_weights: [1., 2.3333] # if only one file ignored

pt_mins: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10., 12., 16.]
pt_maxs: [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10., 12., 16., 24.]

bdt_cuts:
  bkg: [0.01, 0.01, 0.02, 0.02, 0.07, 0.07, 0.07, 0.1, 0.1, 0.1, 0.2, 0.3 ]
  nonprompt: [0.10, 0.12, 0.14, 0.16, 0.18,
              0.20, 0.22, 0.24, 0.26, 0.28,
              0.30, 0.32, 0.34, 0.36, 0.38,
              0.40, 0.42, 0.44, 0.46, 0.48,
              0.50, 0.52, 0.54, 0.56, 0.58,
              0.60, 0.62, 0.64, 0.66, 0.68,
              0.70, 0.72, 0.74, 0.76, 0.78,
              0.80, 0.82, 0.84, 0.86, 0.88,
              0.90, 0.92, 0.94, 0.96, 0.98] # values for cut-variation method (pT differential?)

fit:
  mass_mins: [1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.70, 1.70]
  mass_maxs: [1.99, 1.99, 1.99, 1.99, 1.99, 1.99, 1.99, 1.99, 1.99, 1.99, 2.05, 2.05]
  sgn_funcs: ["gaussian", "gaussian", "gaussian", "gaussian", "gaussian", "gaussian", "gaussian", "gaussian", "gaussian", "gaussian", "gaussian", "gaussian"]
  bkg_funcs: ["chebpol3", "chebpol3", "chebpol3", "chebpol3", "chebpol3", "chebpol3", "chebpol3", "chebpol3", "chebpol3", "chebpol3", "chebpol3", "chebpol3"]

efficiency:
  include_pitomu: True

output:
  rawyields:
    directory: rawyields
    suffix: _dplus_LHC22_LHC23_full
  efficiencies:
    directory: efficiencies
    suffix: _dplus_LHC24g5_LHC24h1_new
