# -----inputs for raw yields --------------------------
fileNameData: /data/lagliett/HF_data/AO2D_TaskDs1MB_train307666.root
treeNameData: O2hfcandresolite
outputRawYield: /home/lagliett/alice/CharmResonancesAnalysis/raw_yield/output/rawYieldDs1_MB.root
filteredDf: filteredTreeTaskDs1_MB.parquet
plotLabel: invMass_Ds1_MB
# -----inputs for efficiencies ------------------------
fileNameMC : /home/lagliett/alice/CharmResonanceAnalysis/data/TreeTaskDs1LHC24g6.root
treeNameRec: O2hfcandresolite
treeNameGen: O2hfgenresolite
outputEff: /home/lagliett/alice/CharmResonancesAnalysis/efficiency/efficiency_Ds1_LHC24g6_TRG.root
# -----particle pdgcode: Ds1:10433, Ds2*:435 -----------
pdgId: 10433
# -----Cuts, same for efficiencies and yields-----------
cutVars: 
  pt:
    min:  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10., 12., 2.] 
    max:  [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10., 12., 24., 24.]
    varname: 'fPt'
    useBachPt: false
  ptBach0:
    min:  [1.0, 2.0, 3.0, 5.0, 8.0, 12., 16.] 
    max:  [2.0, 3.0, 5.0, 8.0, 12., 16., 24.]
    varname: 'fPtBach0'
    useBachPt: false
  invMass:
    min: [ 0.49, 0.49, 0.49, 0.49, 0.49, 0.49, 0.49, 0.49, 0.49, 0.49, 0.49]
    max: [ 0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 0.89]
    varname: 'fM'
    useBachPt: false
  bkgBdtScore:
    min:  [ ~, ~, ~, ~, ~, ~, ~] 
    max:  [ 0.03, 0.08, 0.3, 0.7, 0.8, 0.9, 0.6,]
    varname: 'fMlScoreBkgBach0'
    useBachPt: true
  invMassProng0:
    min:  [ 0.1438, 0.1438, 0.1438, 0.1438, 0.1438, 0.1438, 0.1438] 
    max:  [ 0.1468, 0.1468, 0.1468, 0.1468, 0.1468, 0.1468, 0.1468]
    varname: 'fMBach0'
    useBachPt: true
    parametrized: false
  invMassProng1:
    min:  [ 0.4882, 0.4882, 0.4882, 0.4882, 0.4882, 0.4882, 0.4882, 0.4882, 0.4882, 0.4882, 0.4882] 
    max:  [ 0.5050, 0.5050, 0.5050, 0.5050, 0.5050, 0.5050, 0.5050, 0.5050, 0.5050, 0.5050, 0.5050]
    varname: 'fMBach1'
    useBachPt: false
# -----Invariant mass signal extraction configs-----------
fit:
  mass_mins: [ 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50]
  mass_maxs: [ 0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60]
  sgn_funcs: [ "voigtian", "voigtian", "voigtian", "voigtian", "voigtian", "voigtian", "voigtian", "voigtian", "voigtian", "voigtian"]
  bkg_funcs: [ "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext", "expopowext"]
plot:
  mass_mins: [0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50, 0.50]
  mass_maxs: [0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60, 0.60]
  nbins: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
# -----Efficiency configs---------------------------------
acceptFlags: [1, 4, 6]


