# Inputs:
fileNameData: /home/luca/alice/CharmResonancesAnalysis/data/AO2D_TreeTaskDs1_TriggerLooseCut.root
treeNameData: O2hfcandresolite

fileNameMC: [/home/luca/alice/CharmResonancesAnalysis/data/TRG_g6_303941.root, /home/luca/alice/CharmResonancesAnalysis/data/TRG_h2_302432.root]
mcWeights: [1, 7]
treeNameRec: O2hfcandresolite
treeNameGen: O2hfgenresolite
acceptFlags: [1, 5, 6]

particle: ds1

outputFolder: cutvar_output
outputFilePrefix: cutvar_ds1_trg

# preliminary selections (should bee looser than any successive variation)
cutVars: 
  pt:
    min:  [2.0, 5.0, 8.0, 12.] 
    max:  [5.0, 8.0, 12., 24.]
    varname: 'fPt'
    useBachPt: false
  ptBach0:
    min:  [1.0, 5.0, 8.0, 12.] 
    max:  [5.0, 8.0, 12., 100.]
    varname: 'fPtBach0'
    useBachPt: false
  invMass:
    min: [ 0.49, 0.49, 0.49, 0.49, 0.49, 0.49, 0.49, 0.49, 0.49]
    max: [ 0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 0.89, 0.89]
    varname: 'fM'
    useBachPt: false
  bkgBdtScore:
    min:  [ ~, ~, ~, ~, ~, ~, ~]
    max:  [0.2, 0.2, 0.2, 0.2, 0.2, 0.2] # loose cuts: limits from wagon. Minimum step is 0.001
    varname: 'fMlScoreBkgBach0'
    useBachPt: true
  invMassProng0:
    min:  [ 0.142, 0.142, 0.142, 0.142] 
    max:  [ 0.149, 0.149, 0.149, 0.149]
    varname: 'fMBach0'
    useBachPt: true
    parametrized: false
  invMassProng1:
    min:  [ 0.48, 0.48, 0.48, 0.48, 0.48, 0.48, 0.48] 
    max:  [ 0.5135, 0.5135, 0.5135, 0.5135, 0.5135, 0.5135, 0.5135]
    varname: 'fMBach1'
    useBachPt: false
  itsNCls0:
    min:  [ 4, 4, 4, 4, 4, 4, 4] 
    max:  [ ~, ~, ~, ~, ~, ~, ~]
    varname: 'fItsNClsProngMinBach0'
    useBachPt: false
  tpcRows0:
    min:  [ 70, 70, 70, 70, 70, 70, 70] 
    max:  [ ~, ~, ~, ~, ~, ~, ~]
    varname: 'fTpcNClsCrossedRowsProngMinBach0'
    useBachPt: false
  tpcChi0:
    min:  [ ~, ~, ~, ~, ~, ~, ~] 
    max:  [ 4, 4, 4, 4, 4, 4, 4]
    varname: 'fTpcChi2NClProngMaxBach0'
    useBachPt: false
  itsNCls1:
    min:  [ 0, 0, 0, 0, 0, 0, 0] 
    max:  [ ~, ~, ~, ~, ~, ~, ~]
    varname: 'fItsNClsProngMinBach1'
    useBachPt: false
  tpcRows1:
    min:  [ 70, 70, 70, 70, 70, 70, 70] 
    max:  [ ~, ~, ~, ~, ~, ~, ~]
    varname: 'fTpcNClsCrossedRowsProngMinBach1'
    useBachPt: false
  tpcChi1:
    min:  [ ~, ~, ~, ~, ~, ~, ~] 
    max:  [ 4, 4, 4, 4, 4, 4, 4]
    varname: 'fTpcChi2NClProngMaxBach1'
    useBachPt: false

centralCuts:
  pt:
    min:  [2.0, 5.0, 8.0, 12.] 
    max:  [5.0, 8.0, 12., 24.]
    varname: 'fPt'
    useBachPt: false
  ptBach0:
    min:  [1.0, 2.0, 3.0, 5.0, 8.0, 12., 16.] 
    max:  [2.0, 3.0, 5.0, 8.0, 12., 16., 100.]
    varname: 'fPtBach0'
    useBachPt: false
  invMassProng0:
    min:  [0.143, 0.143, 0.143, 0.143, 0.143, 0.143, 0.143] 
    max:  [0.148, 0.148, 0.148, 0.148, 0.148, 0.148, 0.148]
    varname: 'fMBach0'
    useBachPt: true
    parametrized: false
  invMassProng1:
    min:  [ 0.485, 0.485, 0.485, 0.485, 0.485, 0.485, 0.485] 
    max:  [ 0.5085, 0.5085, 0.5085, 0.5085, 0.5085, 0.5085, 0.5085]
    varname: 'fMBach1'
    useBachPt: false
  bkgBdtScore:
    min:  [ ~, ~, ~, ~, ~, ~, ~]
    max:  [0.06, 0.06, 0.06, 0.06, 0.06, 0.06, 0.06] 
    varname: 'fMlScoreBkgBach0'
    useBachPt: true
  cpaBach1:
    min:  [0.995, 0.995, 0.995, 0.995, 0.995, 0.995, 0.995]
    max:  [~, ~, ~, ~, ~, ~, ~] 
    varname: 'fCpaBach1'
    useBachPt: false
  radiusBach1:
    min:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 
    max:  [~, ~, ~, ~, ~, ~, ~] 
    varname: 'fRadiusBach1'
    useBachPt: false

# variations for systematic uncertainties (assume same pT binning as for preliminary selections)

nonPromptCutvar:
  # Outputs
  configurations:
    - name: "central"
      cuts: [0.0, 0.0, 0.0, 0.0]
    - name: "np_cut_0"
      cuts: [0.22, 0.42, 0.42, 0.40]
    - name: "np_cut_1"
      cuts: [0.27, 0.46, 0.46, 0.44]
    - name: "np_cut_2"
      cuts: [0.32, 0.50, 0.50, 0.48]
    - name: "np_cut_3"
      cuts: [0.37, 0.54, 0.54, 0.52]
    - name: "np_cut_4"
      cuts: [0.42, 0.58, 0.58, 0.56]
    - name: "np_cut_5"
      cuts: [0.47, 0.62, 0.62, 0.60]
    - name: "np_cut_6"
      cuts: [0.52, 0.66, 0.66, 0.64]
    - name: "np_cut_7"
      cuts: [0.57, 0.70, 0.70, 0.68]
    - name: "np_cut_8"
      cuts: [0.62, 0.74, 0.74, 0.72]
    - name: "np_cut_9"
      cuts: [0.67, 0.78, 0.78, 0.76]
    - name: "np_cut_10"
      cuts: [0.72, 0.82, 0.82, 0.80]
    - name: "np_cut_11"
      cuts: [0.77, 0.86, 0.86, 0.84]
    - name: "np_cut_12"
      cuts: [0.82, 0.90, 0.90, 0.88]
    - name: "np_cut_13"
      cuts: [0.87, 0.94, 0.94, 0.92]
    - name: "np_cut_14"
      cuts: [0.92, 0.98, 0.98, 0.96]
    
# raw yield extraction
rawYield:
  # Outputs
  outputFile: output/output_yield_sys_Ds1_trg.root
  optionalRawYieldOutput: output/fitdump_yield_sys_Ds1_trg.root 
  default_fit_config:
    mass_min: 0.50
    mass_max: 0.60
    signal_pdf: "voigtian"
    bkg_pdf: "thr3"
    parameters:
    - name: "mean"
      value: "0.52485"
      min: "0.519"
      max: "0.529"
    - name: "sigma"
      value: "0.001"
      min: "0.0001"
      max: "0.003"
    - name: "width"
      value: "0.00046"
      min: "0.00046"
      max: "0.00046"
    - name: "mTh"
      value: "0.497611"
      min: "0.497611"
      max: "0.497611"
    - name: "l"
      value: "0.5"
      min: "0.1"
      max: "1"
    - name: "alpha"
      value: "0.2"
      min: "-100"
      max: "100"
    - name: "beta"
      value: "50"
      min: "-100"
      max: "100"
    - name: "gamma"
      value: "-500"
      min: "-10000"
      max: "10000"
